### ISSUE TITLE
How delete map element by index?

### ISSUE THREAD

**Issue by delef** [lucaong/immutable#12]
Hi! Thanks for your work!
I need delete first or last element. How I can do this?

**Comment by lucaong** [comment]
Hi @delef, sorry for the delay. Do you mean deleting the first/last element in insertion order from a Map?

That's not directly supported: Map is accessed by key, and it's not sorted. You could keep a second data structure with keys in insertion order.

**Comment by delef** [comment]
Thanks! How to determine capacity for map?

**Comment by lucaong** [comment]
Welcome :)

You can determine the size of a map with [the `Map#size` method](http://lucaong.github.io/immutable/api/Immutable/Map.html#size-instance-method), which returns the number of entries in the Map
