### ISSUE TITLE
Is the project maintained?

### ISSUE THREAD

**Issue by vladfaust** [lucaong/immutable#8]
Hello,

I've checked your project and it either:

* Has specs failed with the latest Crystal (0.26.1)
* Has no any specs to run so it cannot be validated to be up to date
* Has the latest commit dated more than a year ago

Your project is in [Awesome Crystal](https://github.com/veelenga/awesome-crystal) list, so I'd like to ask if the project maintained?

I'll initiate a PR to remove your project from the list if you don't respond positively within 7 days.

I'm sorry if I'm wrong, because I've been checking many shards with automated script.

Thanks,
Vlad.

**Comment by lucaong** [comment]
Hi @vladfaust 
Thanks for notifying me. Yes, the project is maintained. It had fallen a bit behind in supporting recent Crystal versions, as numerous changes to some language core APIs broke it. I must admit I was a bit overwhelmed with the changes, and opted to wait until the language would stabilize a bit.

Prompted by your message, I looked into it again, and I am happy to see that most of the APIs that I use seem to have stabilized in recent versions, so I managed to update my library to support the latest Crystal `v0.26.1`.

I will make try to keep it up to date with newer language releases, as they get published.

**Comment by vladfaust** [comment]
Hi, @lucaong,

I'm not sure if https://github.com/veelenga/awesome-crystal/pull/351 will be merged, but I kindly ask you to follow it. I will drop your shards from the list of removed ones for now 😃

**Comment by lucaong** [comment]
Watching it now. Thanks again for the support!

**Comment by lucaong** [comment]
I also added weekly builds on Travis CI, in case the PR gets merged
